version: '3'
services:
  app:
    container_name: bot_app
    # AQUI ESTÁ A CORREÇÃO: Apontamos para a pasta src onde o Dockerfile mora
    build: ./src
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - db_mysql
    environment:
      - DB_HOST=db_mysql
      - DB_USER=root
      - DB_PASSWORD=senha_root_super_forte_2024
      - DB_NAME=bot_db

  db_mysql:
    container_name: bot_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_root_super_forte_2024
      MYSQL_DATABASE: bot_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: